# Pre-commit hooks configuration
# See https://pre-commit.com for more information
repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Git checks
      - id: check-added-large-files
        args: ['--maxkb=1024']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-new-submodules
      
      # File format checks
      - id: check-json
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: check-toml
      - id: check-xml
      
      # Code quality
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']
      
      # Security
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']

  # TypeScript/JavaScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|ts|jsx|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^8.0.0
          - typescript@^5.0.0
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'

  # Prettier formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]
        additional_dependencies:
          - prettier@^3.0.0

  # Commitizen conventional commits
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock.json

  # Docker hooks
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: Dockerfile.*

  # Documentation
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: ['--fix']
        files: \.md$

  # Custom local hooks
  - repo: local
    hooks:
      # TypeScript compilation check
      - id: typescript-check
        name: TypeScript Compilation Check
        entry: npx tsc --noEmit
        language: system
        types: [ts]
        pass_filenames: false

      # Tests
      - id: run-tests
        name: Run Tests
        entry: npm test
        language: system
        pass_filenames: false
        stages: [pre-push]

      # Build check
      - id: build-check
        name: Build Check
        entry: npm run build
        language: system
        pass_filenames: false
        stages: [pre-push]

      # Security audit
      - id: npm-audit
        name: NPM Security Audit
        entry: npm audit --audit-level high
        language: system
        pass_filenames: false
        stages: [pre-push]

      # Dependency check
      - id: outdated-deps
        name: Check Outdated Dependencies
        entry: npm outdated
        language: system
        pass_filenames: false
        stages: [manual]
        verbose: true

# Global configuration
default_language_version:
  node: system

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false