version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:15-alpine
    container_name: bitcoin-price-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: bitcoin_price_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bitcoin_price_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bitcoin-price-dev-network


  # Development app with hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bitcoin-price-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      UPDATE_INTERVAL: 10000
      SERVICE_COMMISSION: 0.0001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bitcoin_price_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      BINANCE_BASE_URL: https://api.binance.com
      BINANCE_SYMBOL: BTCUSDT
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - dev_logs:/app/logs
    networks:
      - bitcoin-price-dev-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: bitcoin-price-prometheus-dev
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_dev_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - bitcoin-price-dev-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: bitcoin-price-grafana-dev
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_USERS_ALLOW_SIGN_UP: false
    volumes:
      - grafana_dev_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    depends_on:
      - prometheus
    networks:
      - bitcoin-price-dev-network

networks:
  bitcoin-price-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  dev_logs:
    driver: local
  prometheus_dev_data:
    driver: local
  grafana_dev_data:
    driver: local