version: '3.8'

services:
  # PostgreSQL Database for development
  postgres:
    image: postgres:15-alpine
    container_name: bitcoin-price-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: bitcoin_price_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bitcoin_price_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bitcoin-price-dev-network

  # Development app with hot reload
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bitcoin-price-service-dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      PORT: 3000
      UPDATE_INTERVAL: 10000
      SERVICE_COMMISSION: 0.0001
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: bitcoin_price_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      BINANCE_BASE_URL: https://api.binance.com
      BINANCE_SYMBOL: BTCUSDT
      LOG_LEVEL: debug
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
      - dev_logs:/app/logs
    networks:
      - bitcoin-price-dev-network

networks:
  bitcoin-price-dev-network:
    driver: bridge

volumes:
  postgres_dev_data:
    driver: local
  dev_logs:
    driver: local