#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run pre-commit hooks
npx pre-commit run --all-files

# Run type check
npm run type-check

# Run linting
npm run lint

# Run tests
npm run test:pre-commit